Reorder websites based on F# version support
fsharp/fsfoundation pull request #869
Opened 2021-06-07 12:46 UTC by Happypig375

Fixes #868

2021-06-07 14:02 UTC, dsyme requested changes
I am really glad you're looking through the list, giving it a scrub, and agree ordering it differently can be good.

The one thing is that information like "Supports F# 4.6" goes out of date quickly. Please don't add that kind of detail

2021-06-07 14:02 UTC, dsyme commented on use/browser/index.md
> +computer. It includes example code for many of F#'s basic features. It's based on the  [Fable 2 REPL](https://fable.io/repl/). Supports F# 4.6
Information like "Supports F# 4.6" goes out of date quickly. Please don't add this

2021-06-07 14:33 UTC, Happypig375 commented on use/browser/index.md
> +computer. It includes example code for many of F#'s basic features. It's based on the  [Fable 2 REPL](https://fable.io/repl/). Supports F# 4.6
But does anyone update them? F# 4.6 being more than two years old now, most of the websites listed still do not support it. Only two do. I think this would be best for usability?

2021-06-07 14:37 UTC, Happypig375 commented on use/browser/index.md
> +computer. It includes example code for many of F#'s basic features. It's based on the  [Fable 2 REPL](https://fable.io/repl/). Supports F# 4.6
This is especially true for glot.io which is still on the 6-year-old F# 4.0. This indicates that it is not maintained at all.

2021-06-07 15:19 UTC, dsyme commented on use/browser/index.md
> +computer. It includes example code for many of F#'s basic features. It's based on the  [Fable 2 REPL](https://fable.io/repl/). Supports F# 4.6
Well, it's hard to tell, but for fsharp.org it's generally just better not to list information that may go stale.  

Fine to simply remove old entries which use old F#

2021-06-07 16:02 UTC, Happypig375 commented on use/browser/index.md
> +computer. It includes example code for many of F#'s basic features. It's based on the  [Fable 2 REPL](https://fable.io/repl/). Supports F# 4.6
I'd consider F# <5 to be old, but that would remove too much.

2021-06-12 12:06 UTC, Happypig375 commented
Ping

2021-06-12 12:20 UTC, dsyme commented on use/browser/index.md
> +## Deprecated
I'll merge this then just remove these

2021-06-12 12:20 UTC, dsyme approved these changes

2021-06-12 12:20 UTC, merged